### ISSUE TITLE
No need for consolekit anymore

### ISSUE THREAD

**Issue by sebastiansetzer** [codingtony/udev-monitor-hotplug#4]
Since commit 0d33d270a58b1b1480e9d5f2ecb23d37dbee82b0,
$uid isn't used anymore.
So can't you remove the dependency to consolekit?

On my computer, ck-list-sessions doesn't list anything. But I just removed that part of the script (just left the XAUTHORITY line) and it still works.

**Comment by codingtony** [comment]
Do a PR, and I will be glad to merge it

**Comment by brandonio21** [comment]
Let's close the issue since it's been resolved :)
